MàJ éléments réglementaires
etalab/transport-normes-site pull request #29
Opened 2024-12-02 20:10 UTC by TuThoThai

Cette PR correspont à l'issue ouverte [ici](https://github.com/etalab/transport-site/issues/4349).

2024-12-02 20:18 UTC, thbar commented
Je vois une alerte en haut de la PR, qu'il faudra comprendre:

![CleanShot 2024-12-02 at 21 18 26@2x](https://github.com/user-attachments/assets/5903f351-8669-4d6a-ac73-ac97bd39b3aa)

2024-12-02 20:19 UTC, thbar commented
Ah je comprends - @TuThoThai c'est lié à l'usage du caractère `à` dans le nom de ta branche.

2024-12-02 21:06 UTC, TuThoThai commented
@thbar : toutes mes excuses, je n'avais même pas vu que j'avais tapé avec l'accent. Besoin que je le refasse ?

2024-12-02 21:38 UTC, thbar commented
@TuThoThai non je pense que ça ira comme ça ! Merci !

2024-12-03 08:37 UTC, Brewennn commented on config.yml
> +            L'ouverture données statiques, dynamiques, observées et historiques  des déplacements multimodaux est encadrée :
un espace à supprimer entre "historiques" et "déplacements"

2024-12-03 08:40 UTC, Brewennn requested changes
Il y a juste une petite coquille à corriger. Sinon tout est bon ici.

2024-12-03 08:44 UTC, Brewennn commented on content/processus.md
> +- Le profil français  de la norme européenne NeTEx et ses différents composants (appelés “sous-profils”)
espace en trop entre "français" et "de la norme. Est-ce qu'on a besoin de préciser "sous-profils" ? car dans les lignes juste en dessous on parle de profil et je pense que ça peut embrouiller.

2024-12-03 08:46 UTC, Brewennn commented on content/processus.md
> +Ce document a été rédigé dans le cadre des travaux de normalisation menés par le Bureau de normalisation pour les transports, les routes et leurs aménagements (BNTRA), au sein de la Commission de Nor
"Groupe de Travail" en minuscule ou mettre en majuscule le même terme linge 10.

2024-12-03 08:48 UTC, Brewennn commented on content/processus.md
> +> Exemple : NeTEx – Profil France   et son sous profil NeTEx – Profil France - Accessibilité
Espace en trop entre "France" et "et son sous-profil"

2024-12-03 10:15 UTC, Brewennn commented on content/processus.md
> +**Standard** : référentiel ou ensemble de recommandations développées et préconisées par un groupe autre qu’une instance de normalisation nationale ou internationale ou non approuvé par ces dernières
Je propose une autre manière de formuler :

"référentiel ou ensemble de recommandations développés et préconisés par un groupe autre qu’une instance de normalisation nationale ou internationale, ou non approuvés par ces dernières. Le standard est qualifié en tant que tel qu'à partir du moment où le référentiel a une diffusion large. On parle alors de standard de facto (standard de fait). Un standard est ouvert correspond à un référentiel diffusé librement."

2024-12-03 10:16 UTC, Brewennn commented on content/processus.md
> +tout autre document issu d’un groupe de travail du BNTRA ou du PAN dont la gouvernance ne dépend pas directement d’instances de normalisation européennes ou internationales. Ces documents sont généra
ligne 58 à remettre avec la ligne 57 comme pour les autres défintions

2024-12-03 10:17 UTC, Brewennn commented on content/processus.md
> +Dans le reste du document, "documents techniques" fera référence aux profils de normes, standards et spécifications techniques sans distinction.
proposition de petit correctif : Dans le reste du document, le terme "documents techniques" fera référence...

2024-12-03 10:18 UTC, Brewennn commented on content/processus.md
> +- Les explications liées à la création de sous-ensemble de champs ou d’attributs du profil national,
sous-ensembles

2024-12-03 10:20 UTC, Brewennn commented on content/processus.md
> +## La rédaction, modification ou la révision
double saut à la ligne

2024-12-03 10:22 UTC, Brewennn commented on content/processus.md
> +Si le profil est assez "actif", il est également conseillé de le réviser ou modifier assez fréquemment pour ne pas oublier les retours / commentaires reçus ou de laisser les demandes de changer trop
"demandes de changement" plutôt ?

2024-12-03 10:25 UTC, Brewennn commented on content/processus.md
> +- Résolutiojns de toutes les questions (_issues_) ou demandes de changements (Pull Requests) relatives à la version à publier, il peut également être décidé que ces questions ou demandes seront trait
"il peut également être décidé que ces questions ou demandes soient traitées" (au lieu de "seront")

2024-12-03 10:39 UTC, Brewennn commented on content/processus.md
> +Il est à noter qu’à ce jour l’ensemble des profils de NeTEx et SIRI publiés sur le site sont en complément d’une obligation légale d’ouverture des données de transport, c’est-à-dire mentionnés dans d
proposition : "Il est à noter que l’ensemble des profils de NeTEx et SIRI publiés sur le site sont considérés comme officiels du point de vue légal."

2024-12-03 10:41 UTC, Brewennn requested changes
Quelques petits correctifs et proposition de formulation. Ce n'est pas grand chose et je vous laisse valider ou non

2024-12-03 20:42 UTC, TuThoThai commented on content/processus.md
> +Notamment lors de l’initialisation des profils et après création de son chemin de fer, il est très fortement conseillé de travailler sur des petites modifications pour qu’elles soient plus simples à
j'ia changé en "sa structure (ou squelette)". Désolée, terme hérité de mon temps dans l'impression

2024-12-03 20:44 UTC, TuThoThai commented
@Brewennn, j'ai pris en compte toutes tes suggestions. Je te laisse les vérifier et valider officiellement cette PR !

2024-12-04 08:28 UTC, Brewennn approved these changes

2024-12-04 08:53 UTC, Brewennn approved these changes
Désolé je pensais avoir approuvé les changements. voilà qui est fait. On pourra cloturer.

2024-12-04 08:53 UTC, Brewennn approved these changes

2024-12-04 08:56 UTC, Brewennn commented
> Désolé je pensais avoir approuvé les changements. voilà qui est fait. On pourra cloturer.

@TuThoThai, je ne sais pas si je ne suis pas doué mais je n'ai pas l'impression que mon approval soit passé.

2024-12-04 09:02 UTC, Brewennn approved these changes

2024-12-04 09:18 UTC, TuThoThai commented
@thbar : Brewenn a bien approuvé les changements. Mais il semblerait que quelque chose coince. Peux-tu nous aider ? 🙏

2024-12-04 09:19 UTC, Brewennn commented
> @thbar : Brewenn a bien approuvé les changements. Mais il semblerait que quelque chose coince. Peux-tu nous aider ? 🙏

Bien que je mette "approve" et "submit review" on a toujours ce message 
![image](https://github.com/user-attachments/assets/8bae731d-32fb-4c23-a714-4dd62f3afe33)

2024-12-04 09:38 UTC, Brewennn commented
@thbar Le problème vient du bandeau tout en haut. Sur autre PR qui ne l'avait pas, un bandeau me demandant de faire une review était à la palce de celui-ci
![image](https://github.com/user-attachments/assets/7107dfae-5880-4ea5-b063-e13e3f30c8e7)

2024-12-04 09:40 UTC, closed without merging

2024-12-04 10:32 UTC, thbar commented
@TuThoThai tu confirmes que cette PR est remplacée par #30 ?